# Berksfile
#
# maintainer:: Exosphere Data, LLC
# maintainer_email:: chef@exospheredata.com
#
# Copyright:: 2018, Exosphere Data, LLC, All Rights Reserved.
#

source 'https://supermarket.chef.io'

cookbook 'veeam'
